### ISSUE TITLE
[Config serveur] Gestion des droits utilisateurs

### ISSUE THREAD

**Issue by edouardalvescamilo** [indydedeken/ProjetRD#11]
Le fichier gérant les droits des utilisateurs est à revoir sur la branche [Script-config-radicale](https://github.com/indydedeken/ProjetRD/tree/Script-config-radicale). 

En cause une erreur lors du démarrage de Radicale via WSGI. Vérifier le respect de la synthaxe dans le fichier rights.

Exemple type:
```
[admin]
user: ^admin.*$
collection: .*
permission: r
```

N.B: Etudier la possibilité de gérer les différentes authentifications via des regex. Revoir la modélisation des droits pour les caractériser de la manière suivante: adminprof en READ sur toutes les collections, un utilisateur typé "Enseignants" en READ/WRITE sur les collections lui appartenant.

**Comment by edouardalvescamilo** [comment]
Nouvelle piste à étudier : l'utilisation de l'arborescence.

Actuellement on utilise le procédé suivant pour récupérer un calendrier : 
- localhost/Enseignants/benzakki_judith.ics/

Il faudrait plutôt utiliser une arborescence de ce type là : 
- localhost/Enseignants/**jbenzak1**/benzakki_judith.ics/

**Comment by edouardalvescamilo** [comment]
Les fichiers de droit ont été mis à jour sur le serveur radicale edouardalvescamilo.ovh. Les mots de passe sont désormais cryptés en MD5.

Les résultats des tests effectués valident les opérations effectuées.

**Comment by indydedeken** [comment]
md5 ?

**Comment by edouardalvescamilo** [comment]
Petite confusion... Les mots de passes sont désormais cryptés avec la méthode "crypt" et non plus en MD5.
