### ISSUE TITLE
Harmonisation des mots de passe

### ISSUE THREAD

**Issue by edouardalvescamilo** [indydedeken/ProjetRD#13]
Nous devons trouver une solution en ce qui concerne la gestion des mots de passe utilisés dans le système VT_AGENDA. J'aimerais disposer de votre avis @desiderius77.

Concrètement les mots de passe sont actuellement cryptés dans la base via **MD5**, hors l'authentification utilisant **mod_authn_dbd** doit utiliser des méthodes de cryptage gérées par Apache.
Les méthodes "**htpasswd**" et "**crypt**" sont actuellement gérées par Apache, ce qui n'est malheureusement pas le cas de MD5.

**Comment by Desiderius77** [comment]
Si je comprends bien, il y incompatibilité totale entre MySQL et Apache en matière de cryptage ? Vous n'avez pas trouvé de méthode commune employable ?

Je n'ai pas de solution miracle dans ce cas : il faut choisir l'on ou l'autre ( je pense que Apache serait mieux)
Sur internet j'ai trouvé ça : 
"Le niveau de cryptage des mots de pass de .htpasswd est défini dans le .htaccess correspondant:
AuthType Basic ---> .htpaswd crypté sur 8 carct

AuthType Digest ---> .htpaswd crypté sur 15 carct (MD5) (attention ne marche pas toujours avec IE ??) 

Vous avez essayé je suppose ?

AuthType Digest ---> .htpaswd crypté sur 15 carct (MD5) (attention ne marche pas toujours avec IE ??)

**Comment by indydedeken** [comment]
@Desiderius77, 
La méthode de cryptage **crypt** semble très bien fonctionner dans MySQL et dans le virtual host (mod_authn_dbd) d'après nos tests.

Si nous adoptons cette solution, alors **tous les mots de passe/codes sources d'authentification (*actuellement basés sur MD5*) de l'application VT_Agenda devrons être modifiés**.

**Comment by Desiderius77** [comment]
Oh dans ce cas là pas de soucis : l
Les utilisateurs mettront de nouveaux mots de passe

**Comment by indydedeken** [comment]
Ok, très bien merci. 
Nous informons le projet VT2 en créant une issue.

**Comment by indydedeken** [comment]
L'issue est corrigé chez nous et en PULL REQUEST chez VT2.
