### ISSUE TITLE
[Radicale] Restreindre l'accès aux agendas au seul mode "read"

### ISSUE THREAD

**Issue by indydedeken** [indydedeken/ProjetRD#5]
Comme vu lors de la présentation, les enseignants ne sont intéressés que par le mode "read".

Procéder comme cela dans le fichier *ProjetRD/serveur RADICALE/etc/radicale/rights* pour les **admin** : 
`permission: r`

### Attention :
/ ! \ Faire la modification en réel aussi sur le serveur www.edouardalvescamilo.ovh.

**Comment by edouardalvescamilo** [comment]
La modification se passe en deux niveaux : créer un compte sur la base de données permettant de s'authentifier avec la nouvelle méthode reposant sur mod_authn_dbd puis gérer les accès dans le fichier rights. 

Je m'en charge dès que possible.

**Comment by edouardalvescamilo** [comment]
La modification a été effectuée. Le compte "adminprof" avec un accès READ sur l'ensemble des collections est désormais disponible.
