### ISSUE TITLE
[Radicale] Associer les comptes Enseignant aux collections

### ISSUE THREAD

**Issue by indydedeken** [indydedeken/ProjetRD#6]
Comme nous en avions déjà parler, il faudrait mettre en place une solution pour **que les comptes des enseignants de la base MySQL (*login + mdp*) soient utilisés par Radicale**.

De telle manière que chacun puisse avoir son couple identifiant et mot de passe servant à la consultation de l'application et du calendrier. 

Précisions : 
- le mot de passe en base est stocké en MD5 nature (sans grain de sel),
- à ce jour, le login (adminprof) ainsi que le mdp (adminprof) sont stockés en dur dans le code.

**Comment by edouardalvescamilo** [comment]
Donc voila mes avancées concernant le système d'authenfication de notre serveur CalDAV.

Comme vous le savez tous les deux, notre solution repose sur WSGI comme l'a gentiment demandé notre très cher Didier.

Nous devons donc pour cela trouver un moyen de gérer ses authenfications via HTTP. Il s'avère qu'Apache dispose d'un module "mod_authn_dbd" permettant de gérer les connections sur un VirtualHost à travers l'execution d'une requete SQL.

Lorsqu'une requete "http://my.server.com:5232/anna/calendar.ics/", il faudrait donc pouvoir recuperer le "anna", qui correspond au proprietaire de la collection "calendar" puis verifier que le mot de passe fournit lors de la connection via Apache correspond effectivement avec le mot de passe contenu en base. 

Il reste ensuite á definir les droits sur les differentes collections. Celles en standart (celles gérées par l'application) seraient donc en READ ONLY, les autres seraient donc en READ AND WRITE, l'authenfication via Apache se chargant dès le départ de virer les identifiants rejetés. Pour éviter de fournir les mot de passe pour les collections en standart, il faudrait trouver un moyen pour les envoyer directement dans la requete comme on le fait déjà pour la méthode via HTACCESS.

http://httpd.apache.org/docs/2.2/mod/mod_authn_dbd.html
http://tavie.onsenfout.com/2011/05/28/authentification-apache-avec-une-table-mysql-dutilisateurs/
http://www.helicontech.com/ape/doc/mod_authn_dbd.htm

**Comment by edouardalvescamilo** [comment]
Afin que ce système fonctionne, il est nécessaire de crypter les mots de passe avec des méthodes de cryptage reconnues par Apache, ce qui n'est pas le cas actuellement.

Après adaptation et vérification, il s'avère que la méthode d'authentification fonctionne. Il est cependant nécessaire d'adapter les mots de passes afin de les rendre compatibles avec cette méthode.

Il faut donc étudier la faisabilité de l'opération

**Comment by indydedeken** [comment]
Ok merci, je pense que tu peux fermer cette issue.
Par contre @edouardalvescamilo peux-tu créer une autre issue en évoquant ce problème de mdp en clair/absence de MD5. 

*Mémo : Il faudra faire un tour des issues ouvertes lors de la présentation.*
