### ISSUE TITLE
Dysfonctionnement téléchargement/non-téléchargement de .ics

### ISSUE THREAD

**Issue by indydedeken** [indydedeken/ProjetRD#7]
J'avais corrigé les NO_DATA, **merci de tester avant de commit**.

Le bug vient du commit [6945eb9021b8424a8f1e2c8a813f225f9f408456](https://github.com/indydedeken/ProjetRD/commit/6945eb9021b8424a8f1e2c8a813f225f9f408456?diff=split) et de la duplication du ```echo "NO_DATA"```.

icsprof.php est corrigé. Merci de faire la correction de icsetudiant.php, icsgroupe.php, icsmateriel.php, icssalle.php sur ce modèle > [742c70de25dae4b15157da1e21993f605a9c1dde](https://github.com/indydedeken/ProjetRD/commit/742c70de25dae4b15157da1e21993f605a9c1dde).

**Comment by indydedeken** [comment]
@Nicolasmar91 action ?

**Comment by Nicolasmar91** [comment]
Réaction. 
Il semble que le Sync n'avait pas fonctionné... je l'avais corrigé dans la foulé il y a 2 semaines, autant pour moi.
