### ISSUE TITLE
Site / Serveur RADICALE

### ISSUE THREAD

**Issue by indydedeken** [indydedeken/ProjetRD#8]
Il y a deux dossier à la racine du site : 
- Site, pour l'application VT Agenda uniquement, 
- Serveur RADICALE, tout ce qui concerne le serveur RADICALE càd CalDAV.

@Nicolasmar91 dans ton dernier commit tu as mis les fichiers `rights` et `users` dans le dossier /Site/config

Merci de les supprimer pour les placer au bon endroit dans le dossier /Serveur Radicale

**Comment by indydedeken** [comment]
@Nicolasmar91 action ?

**Comment by Nicolasmar91** [comment]
Ce sont des fichiers temporaire, j'ai pas vérifié qu'ils fonctionnaient à
cause du problème qui est que l'on ne sait plus avec quel algo on avait
crypté les mots de passes du fichier actuellement en place. Pour ça qu'ils
sont ici, pour ne pas écrasé les autres fichiers.

Je suis malade aujourd'hui, on voit ça demain

**Comment by indydedeken** [comment]
C'est exactement pour cela qu'on utilise Git : **pour permettre un suivi des codes sources et de retrouver le cas échéant un fichier dans un état antérieur**.

Merci de les écraser s'ils fonctionnent. Sinon tu fais une branche... et tu procéderas à la pull-request en temps voulu.

**Comment by indydedeken** [comment]
Pour info : 

@Nicolasmar91 a créé la branche __Script-config-radicale__. Cette branche héberge : 
- une config des users
- une config de leurs droits 
(Commit 51a9a42fa282d459eaa62d7c7e137b45f9bdb68c)

Mais d'après les dernières infos de @edouardalvescamilo, nous n'aurons plus besoin de ce fichier "users". Me trompe-je ?

**Comment by edouardalvescamilo** [comment]
@indydedeken : Effectivement les utilisateurs sont désormais gérés intégralement par la base de données. Il est donc désormais inutile de fournir le fichier user pour gérer les différents utilisateurs du système.
