### ISSUE TITLE
[Config serveur] Utiliser les identifiants/mdp de connexion déjà existants

### ISSUE THREAD

**Issue by indydedeken** [indydedeken/ProjetRD#9]
_Je créé l'issue car elle n'est pas formalisée depuis la clôture de #6_

Nous utilisons actuellement des comptes utilisateurs créés par nous même (_ex: adminprof_).
Il faudrait que la config se mêle avec la base MySQL, cf : mod_authn_dbd.

@edouardalvescamilo t'es sur le sujet ?

**Comment by edouardalvescamilo** [comment]
Alors oui je suis dessus et la système d'authentification est en partie fonctionnel. Un bug relatif au virtualhost demeure néanmoins, la relation entre l'authentification en mode dbd et l'utilisation de deamon pour lancer radicale via WSGI posant soucis. Je me concentre sur ce point pour le rendre au plus vite fonctionnel.

**Comment by edouardalvescamilo** [comment]
La procédure d'authentification est désormais fonctionnelle. Je vais procéder à une mise à jour de la documentation rattachée au projet afin de la faire correspondre avec les dernières modifications effectuées.

Ouverture d'une nouvelle issue concernant un problème rencontré dans le fichier rights dans #11.
